### PR TITLE
Add `.syntax--` prefix

### PR DESCRIPTION
**Pull request by Antikythera**
Fix for the `syntax` prefix

### CODE REVIEW

**Comment by simeydotme** [comment]
hi, @Antikythera , is this something in a new version of Atom?
does it break backwards compatibility?

I actually haven't used Atom for a while; if you could point me to a changelog/blog with info I can merge this! :) thanks for your hard effort! 🙇 

(i did search for info, but I couldn't find any 😕 )

**Comment by Antikythera** [comment]
>Starting from Atom v1.13.0, the contents of atom-text-editor elements are no longer encapsulated >within a shadow DOM boundary. This means you should stop using :host and ::shadow pseudo->selectors, and prepend all your syntax selectors with syntax--. 

From the atom Deprecation Cop :)
https://github.com/atom/atom/pull/12903 This is the commit that introduced this.

**Comment by simeydotme** [comment]
great, thanks so much for the links!
just read through and understand the reasons now... maybe I can try Atom again it seems the perf is getting better! 💃

**Comment by simeydotme** [comment]
I do consider this a breaking change, though; So let's put the version up to `1.0.0` and make a note in the **readme** about version `1.0.0+` of Gooey theme only working with `Atom 1.13.0+`... how does that sound?

Would you be up for adding those changes to the PR @Antikythera ? if not possible I will amend in due course 😸

**Comment by Antikythera** [comment]
Sounds good 😄 
I hope this suffices!

**Review by simeydotme — APPROVED** [review]
Thanks for the effort @Antikythera ! great work.

**Pull request merged**
